name: Build and Release

on:
  workflow_dispatch:  # 手動トリガー
  push:
    tags:
      - 'v*'  # タグ発行時のトリガー

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Rebuild PyInstaller Bootloader
      run: |
        pip install wheel
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller/bootloader
        python ./waf all
        cd ..
        pip install .
        cd ..
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --onefile --name auto-tag-anict main.py
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/auto-tag-anict.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 